# Form implementation generated from reading ui file 'sf_app/gui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(278, 305)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verify_checkbox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.verify_checkbox.setObjectName("verify_checkbox")
        self.horizontalLayout_2.addWidget(self.verify_checkbox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fano_radio = QtWidgets.QRadioButton(parent=self.groupBox)
        self.fano_radio.setChecked(True)
        self.fano_radio.setObjectName("fano_radio")
        self.verticalLayout_3.addWidget(self.fano_radio)
        self.huffman_radio = QtWidgets.QRadioButton(parent=self.groupBox)
        self.huffman_radio.setObjectName("huffman_radio")
        self.verticalLayout_3.addWidget(self.huffman_radio)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.compress_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.compress_button.setObjectName("compress_button")
        self.horizontalLayout_3.addWidget(self.compress_button)
        self.decompress_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.decompress_button.setObjectName("decompress_button")
        self.horizontalLayout_3.addWidget(self.decompress_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "SF Archiver"))
        self.verify_checkbox.setText(_translate("MainWindow", "Verify CRC32 checksum"))
        self.groupBox.setTitle(_translate("MainWindow", "Compression algorithm"))
        self.fano_radio.setText(_translate("MainWindow", "Shannon-Fano"))
        self.huffman_radio.setText(_translate("MainWindow", "Huffman"))
        self.compress_button.setText(_translate("MainWindow", "Compress"))
        self.decompress_button.setText(_translate("MainWindow", "Decompress"))
