# Form implementation generated from reading ui file 'sf_app/gui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(280, 300)
        MainWindow.setMinimumSize(QtCore.QSize(280, 300))
        MainWindow.setMaximumSize(QtCore.QSize(280, 312))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("sf_app/gui/img/sf_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(36, 36, 36);\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: white;\n"
"    color: black;\n"
"    height: 30px;\n"
"    border: none;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:!enabled {\n"
"    background-color: rgb(154, 153, 150);\n"
"    color: rgb(61, 56, 70);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(244, 243, 242);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(222, 221, 218);\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width:                  10px;\n"
"    height:                 10px;\n"
"    border:                 2px solid rgb(119, 118, 123);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: none;\n"
"}\n"
"\n"
"QRadioButton {\n"
"    color: white;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width:                  10px;\n"
"    height:                 10px;\n"
"    border-radius:          7px;\n"
"    border:                 2px solid rgb(119, 118, 123);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:      none;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    color: white;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: white;\n"
"}\n"
"\n"
"QStatusBar{\n"
"    color: white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Cantarell Light")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextBrowserInteraction)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.version_label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        self.version_label.setFont(font)
        self.version_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.version_label.setObjectName("version_label")
        self.horizontalLayout_4.addWidget(self.version_label)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(25)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fano_radio = QtWidgets.QRadioButton(parent=self.groupBox)
        self.fano_radio.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.fano_radio.setChecked(True)
        self.fano_radio.setObjectName("fano_radio")
        self.verticalLayout_3.addWidget(self.fano_radio)
        self.huffman_radio = QtWidgets.QRadioButton(parent=self.groupBox)
        self.huffman_radio.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.huffman_radio.setObjectName("huffman_radio")
        self.verticalLayout_3.addWidget(self.huffman_radio)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verify_checkbox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.verify_checkbox.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.verify_checkbox.setChecked(True)
        self.verify_checkbox.setObjectName("verify_checkbox")
        self.horizontalLayout_2.addWidget(self.verify_checkbox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.compress_button = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.compress_button.setFont(font)
        self.compress_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.compress_button.setObjectName("compress_button")
        self.horizontalLayout_3.addWidget(self.compress_button)
        self.decompress_button = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.decompress_button.setFont(font)
        self.decompress_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.decompress_button.setObjectName("decompress_button")
        self.horizontalLayout_3.addWidget(self.decompress_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SF Archiver"))
        self.label_2.setText(_translate("MainWindow", "<a href=\"https://github.com/Yarosvet/sf_archiver\" style=\"color: white\">Visit GitHub</a>"))
        self.version_label.setText(_translate("MainWindow", "v1.0"))
        self.label.setText(_translate("MainWindow", "SF Archiver"))
        self.groupBox.setTitle(_translate("MainWindow", "Compression algorithm"))
        self.fano_radio.setText(_translate("MainWindow", "Shannon-Fano"))
        self.huffman_radio.setText(_translate("MainWindow", "Huffman"))
        self.verify_checkbox.setText(_translate("MainWindow", "Verify CRC32 checksum"))
        self.compress_button.setText(_translate("MainWindow", "Compress"))
        self.decompress_button.setText(_translate("MainWindow", "Decompress"))
